version: "3.9"
services:
  validator:
    image: arashidos/axelar:latest
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "start-node"
    ports:
      - "${PORT_RPC}:26657"
      - "${PORT_PEER}:26656"
      - "${PORT_API}:1317"
      - "${PORT_GRPC}:9090"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      lava:
    volumes:
      - ./helpers.sh:/opt/helpers.sh
      - axelar:/root/.axelar
volumes:
  axelar:
    external: false
networks:
  axelar:
    external: true
    name: axelar