version: "3.9"
services:
  node:
    image: arashidos/axelar:latest
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "start-node"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      public:
    volumes:
      - ./helpers.sh:/opt/helpers.sh
      - axelar:/root/.axelar
volumes:
  axelar:
    external: false
networks:
  public:
    external: true
    name: public